# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 11:38
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('alias', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': '"csvtests_country"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CSVImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default=b'csvimport.Item', help_text=b'Please specify the app_label.model_name', max_length=255)),
                ('field_list', models.TextField(blank=True, help_text=b'Enter list of fields in order only if\n                                     you dont have a header row with matching field names, eg.\n                                     "column1=shared_code,column2=org(Organisation|name)"')),
                ('upload_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=''), upload_to=b'csv')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('encoding', models.CharField(blank=True, max_length=32)),
                ('upload_method', models.CharField(choices=[(b'manual', b'manual'), (b'cronjob', b'cronjob')], default=b'manual', max_length=50)),
                ('error_log', models.TextField(help_text=b'Each line is an import error')),
                ('import_date', models.DateField(auto_now=True)),
                ('import_user', models.CharField(blank=True, default=b'anonymous', help_text=b'User id as text', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_id', models.PositiveIntegerField()),
                ('natural_key', models.CharField(max_length=100)),
                ('csvimport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvimport.CSVImport')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE', models.PositiveIntegerField(default=0)),
                ('code_share', models.CharField(help_text=b'Cross-organization item code', max_length=32)),
                ('code_org', models.CharField(help_text=b'Organization-specfific item code', max_length=32)),
                ('description', models.TextField(null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(max_length=10, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csvimport.Country')),
            ],
            options={
                'db_table': 'csvtests_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'csvtests_organisation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'csvtests_unitofmeasure',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvimport.Organisation'),
        ),
        migrations.AddField(
            model_name='item',
            name='uom',
            field=models.ForeignKey(help_text=b'Unit of Measure', on_delete=django.db.models.deletion.CASCADE, to='csvimport.UnitOfMeasure'),
        ),
    ]
